---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  environment:
    NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    VERSION: "{{ lookup('env','VERSION') }}"
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}" 
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  # environment:
  #   # Add more env vars here
  #   - ENVIRONMENT: production
  #   - TYPEORM_CONNECTION: postgres
  #   - TYPEORM_ENTITIES: ./modules/domain/**/*.entity{.ts,.js}
  #   - TYPEORM_HOST: uda-database.cdaduydnc6bp.us-east-1.rds.amazonaws.com
  #   - TYPEORM_PORT: 5432
  #   - TYPEORM_USERNAME: postgres
  #   - TYPEORM_PASSWORD: mypassword
  #   - TYPEORM_DATABASE: postgres  
  # #environment:
  #  NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
  #  VERSION: "{{ lookup('env','VERSION') }}"
  #  ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}" 
  #  TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
  #  TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
  #  TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
  #  TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
  #  TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
  #  TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
  #  TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
  #  TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
  #  TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        #delay: 60
        timeout: 600

    - name: "install python for Ansible."
      become: yes
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - setup:
      #apt:
      #  name: "python3-pip"
      #  update_cache: yes
      #  state: present
    #- name: 'Wait port 22 to become reachable/usable.'
    #  wait_for:
    #    port: 22

  roles:
    - configure-server
    - configure-prometheus-node-exporter
