
##- name: "Move files to server"
##  become: true
##  unarchive:
##    src: /root/project/backend.tar.gz
##    dest: /home/ubuntu

##- name: "install package"
##  shell: |
##    cd /home/ubuntu/backend
##    sudo npm install
##- name: "run migrations"
##  shell: |
##    cd /home/ubuntu/backend
##    sudo npm run migrations
##- name: Start PM2
##  shell: |
##    cd /home/ubuntu/backend
##    pm2 start npm --name backend -- start


#---
#- name: "Creates backend app directory"
#  file:
#    path: ~/backend-app
#    state: directory

#- name: "Unarchive backend files"
#  unarchive:
#    src: artifact.tar.gz
#    dest: ~/backend-app

#- name: "Installing Node Dependencies"
#  shell: |
#    cd ~/backend-app
#    npm i

#- name: "Executing Node app with PM2"
#  shell: |
#    cd ~/backend-app/dist
#    pm2 stop default
#    pm2 start main.js

#  register: execute_node

#- name: print message
#  debug:
#    msg: "{{ execute_node.stdout_lines }}"

#- name: "Configure pm2 to start as service"
#  shell: |
#    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#    pm2 save


- name: "Unarchive files and move to ec2"
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/

# - name: "install node_modules"
#   become: true
#   command: npm install
#   args:
#     chdir: /home/ubuntu/backend

# - name: "build npm packages"
#   command: npm run build
#   args:
#     chdir: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i


- name: "--------------------log----------------------"
  command: ls
  args:
    chdir: /home/ubuntu/backend/dist

- name: "Exporting environments"
  shell: |
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_HOST=uda-database.cdaduydnc6bp.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=mypassword
    export TYPEORM_DATABASE=postgres
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    
- name: "start server"
  command: pm2 start main.js --name=backend
  args:
    chdir: /home/ubuntu/backend/dist

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

#- name: "start server"
#  command: pm2 start main.js --name=backend
#  args:
#    chdir: /home/ubuntu/backend/dist