
#########WORKING#######################
#- name: "Unarchive files and move to ec2"
#  unarchive:
#    src: ~/project/backend.tar.gz
#    dest: /home/ubuntu/
#########WORKING#######################
#########REPLACEMENT#######################
# - name: Create Backend Directory
#   file:
#     path: /home/ubuntu/backend
#     state: directory

# - copy:
#     src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
#     dest: /home/ubuntu/backend

# - name: Extract artifact.tar.gz to EC2 
#   unarchive:
#     src: artifact.tar.gz
#     dest: /home/ubuntu/backend

# - name: "Installing Node Dependencies"
#   shell: |
#     cd /home/ubuntu/backend
#     npm i

# - name: Start the app
#   shell: |
#     export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
#     export TYPEORM_HOST=uda-database.cdaduydnc6bp.us-east-1.rds.amazonaws.com
#     export TYPEORM_PORT=5532
#     export TYPEORM_USERNAME=postgres
#     export TYPEORM_PASSWORD=mypassword
#     export TYPEORM_DATABASE=postgres
#     export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
#     export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
#     pm2 stop default
#     pm2 start -f /home/ubuntu/backend/dist/main.js

#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

#########REPLACEMENT#######################

#- name: "Exporting environments"
#  shell: |
#    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
#    export TYPEORM_HOST=uda-database.cdaduydnc6bp.us-east-1.rds.amazonaws.com
#    export TYPEORM_PORT=5532
#    export TYPEORM_USERNAME=postgres
#    export TYPEORM_PASSWORD=mypassword
#    export TYPEORM_DATABASE=postgres
#    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
#    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    
#- name: "start server"
#  command: pm2 start main.js --name=backend
#  args:
#    chdir: /home/ubuntu/backend/dist


---
  - name: install rsync on the ansible controller
    become: yes
    connection: local
    package:
      name: 
        - openssh
        - rsync
      state: present
      
  - name: "move files to server"
    become: yes
    synchronize:
      src: /root/project/backend/dist
      dest: ./udapeople
      recursive: true

  - name: "move node modules"
    become: yes
    synchronize:
      src: /root/project/backend/node_modules
      dest: ./udapeople
      recursive: true

  - name: "run server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: ./udapeople/dist
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
