
#########WORKING#######################
- name: "Unarchive files and move to ec2"
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/
#########WORKING#######################
#########REPLACEMENT#######################
- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- copy:
    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

#########REPLACEMENT#######################


- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i


- name: "--------------------log----------------------"
  command: ls
  args:
    chdir: /home/ubuntu/backend/dist

- name: "Exporting environments"
  shell: |
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_HOST=uda-database.cdaduydnc6bp.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=mypassword
    export TYPEORM_DATABASE=postgres
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    
- name: "start server"
  command: pm2 start main.js --name=backend
  args:
    chdir: /home/ubuntu/backend/dist

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

#- name: "start server"
#  command: pm2 start main.js --name=backend
#  args:
#    chdir: /home/ubuntu/backend/dist